spring:
    datasource:
        url: jdbc:sqlserver://eu-az-sql-serv1.database.windows.net:1433;databaseName=daqgse4p6zm0j0m
        username: ub5py3x75glz9b1
        password: tv6BDtqzBtRW*d&YnhO#Yn13?
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#        url: jdbc:sqlserver://localhost:1433;databaseName=MiniChatDB
#        username: sa
#        password: 123
#        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.SQLServer2012Dialect
                format_sql: true